"""
Character Engine for Headcanon.

The reasoning engine responsible for constructing a character's context from the
Universe and World State, then generating in-character responses.

Reference: docs/engines/02_character_engine.md
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from app.engines.memory_engine import MemoryEngine
from app.engines.relationship_engine import RelationshipEngine
from app.world.character import Character
from app.world.memory import Memory
from app.world.relationship import Relationship
from app.world.universe import Universe
from app.world.world_state import WorldState

logger = logging.getLogger(__name__)

_PROMPT_DIR = Path(__file__).parent.parent / "prompts" / "characters"

# Forbidden meta-phrases that break character immersion
_FORBIDDEN_AI_PHRASES = [
    "as an ai",
    "language model",
    "chatgpt",
    "openai",
    "prompt",
    "context window",
    "i cannot fulfill",
]


class CharacterEngineResponse(BaseModel, frozen=True):
    """
    Structured response generated by the Character Engine.

    Does NOT mutate world state, timeline, or storage directly.
    """

    character_id: str = Field(min_length=1)
    dialogue: str = Field(min_length=1)
    emotion: str | None = None
    actions: list[str] = Field(default_factory=list)
    memory_candidates: list[dict[str, Any]] = Field(default_factory=list)
    relationship_changes: list[dict[str, Any]] = Field(default_factory=list)
    world_effects: list[str] = Field(default_factory=list)
    follow_up_actions: list[str] = Field(default_factory=list)


class CharacterEngine:
    """
    The reasoning engine for Headcanon character interactions.

    Responsibilities:
      - Load character profile, WorldState, nearby entities, memories, and relationships
      - Build minimal deterministic LLM context
      - Execute character prompts (character_response.txt, speech_style.txt, personality_guard.txt)
      - Validate in-character response and reject AI meta-language or rule violations
      - Return structured CharacterEngineResponse

    Args:
        ai_client: Injected AI client implementing generate(prompt: str) -> str.
        memory_engine: Optional MemoryEngine instance for memory retrieval.
        relationship_engine: Optional RelationshipEngine instance for social context.
        prompt_dir: Path to character prompt directory.
    """

    def __init__(
        self,
        ai_client: Any,
        memory_engine: MemoryEngine | None = None,
        relationship_engine: RelationshipEngine | None = None,
        prompt_dir: Path = _PROMPT_DIR,
    ) -> None:
        if ai_client is None:
            raise ValueError("CharacterEngine requires a valid AIClient.")
        self.ai_client = ai_client
        self.memory_engine = memory_engine or MemoryEngine(ai_client, prompt_dir)
        self.relationship_engine = relationship_engine or RelationshipEngine(ai_client, prompt_dir)
        self.prompt_dir = prompt_dir
        self._prompts: dict[str, str] = {}
        self._load_prompts()

    def _load_prompts(self) -> None:
        """Pre-load character prompts from disk."""
        required = [
            "character_response.txt",
            "speech_style.txt",
            "personality_guard.txt",
        ]
        for filename in required:
            path = self.prompt_dir / filename
            if not path.exists():
                raise FileNotFoundError(f"Required prompt file not found: {path}")
            self._prompts[filename] = path.read_text(encoding="utf-8")

    def build_context(
        self,
        character: Character,
        world_state: WorldState,
        universe: Universe,
        user_action: str,
        memories: list[Memory] | None = None,
        relationships: list[Relationship] | None = None,
        scene_narration: str | None = None,
    ) -> dict[str, str]:
        """
        Build minimal, deterministic context for the LLM.

        Never sends the entire universe. Include only what is relevant.

        Args:
            character: Target Character model.
            world_state: Current WorldState model.
            universe: Canonical Universe model.
            user_action: Player input or action string.
            memories: Optional candidate memories.
            relationships: Optional candidate relationships.
            scene_narration: Current scene text/narration.

        Returns:
            Dict of prompt template variable key-value pairs.
        """
        # Character State from WorldState
        char_state = world_state.characters.get(character.id)
        current_location_id = char_state.location if char_state else None
        current_health = char_state.health if char_state else "Healthy"
        current_emotion = char_state.emotion.value if char_state and char_state.emotion else "Calm"

        # Nearby Occupants & Objects
        nearby_characters: list[str] = []
        nearby_objects: list[str] = []
        if current_location_id and current_location_id in world_state.locations:
            loc_state = world_state.locations[current_location_id]
            nearby_characters = [cid for cid in loc_state.occupants if cid != character.id]
            nearby_objects = list(loc_state.objects)

        # Retrieve relevant memories via MemoryEngine
        active_memories = memories or []
        retrieved_mems = self.memory_engine.retrieve_memories(
            character_id=character.id,
            memories=active_memories,
            query=user_action,
            limit=5,
        )
        memory_context = self.memory_engine.build_memory_context(retrieved_mems)

        # Build relationship context via RelationshipEngine
        active_rels = relationships or universe.relationships
        rel_context = self.relationship_engine.build_relationship_context(
            active_rels, character_id=character.id
        )

        # Rules context (immutable world rules)
        rule_lines = [f"- {r.name}: {r.description}" for r in universe.world_rules[:5]]
        rules_context = "\n".join(rule_lines) if rule_lines else "Standard physical laws apply."

        # Character Profile Summary
        profile_str = (
            f"Name: {character.name}\n"
            f"Species: {character.species or 'Human'}\n"
            f"Occupation: {character.occupation or 'None'}\n"
            f"Description: {character.description}\n"
            f"Personality Traits: {', '.join(character.personality.traits)}\n"
            f"Speech Tone: {character.speech.tone or 'Natural'}\n"
            f"Current Goal: {character.goals[0].title if character.goals else 'None'}"
        )

        # World State Summary
        world_str = (
            f"Day: {world_state.time.day}, Hour: {world_state.time.hour}\n"
            f"Location: {current_location_id or 'Unknown'}\n"
            f"Health: {current_health}\n"
            f"Emotion: {current_emotion}\n"
            f"Nearby Characters: {', '.join(nearby_characters) if nearby_characters else 'None'}\n"
            f"Nearby Objects: {', '.join(nearby_objects) if nearby_objects else 'None'}"
        )

        return {
            "character_profile": profile_str,
            "current_world_state": world_str,
            "current_scene": scene_narration or f"Location: {current_location_id}",
            "character_memories": memory_context,
            "relationship_data": rel_context,
            "timeline_position": f"Day {world_state.time.day}",
            "user_action": user_action,
            "conversation_context": f"User action: {user_action}",
            "universe_rules": rules_context,
        }

    def generate_response(
        self,
        character_id: str,
        world_state: WorldState,
        universe: Universe,
        user_action: str,
        memories: list[Memory] | None = None,
        relationships: list[Relationship] | None = None,
        scene_narration: str | None = None,
    ) -> CharacterEngineResponse:
        """
        Execute character reasoning and generate a validated in-character response.

        Args:
            character_id: Target character ID.
            world_state: Current WorldState.
            universe: Canonical Universe.
            user_action: User prompt or action string.
            memories: Candidate memories.
            relationships: Candidate relationships.
            scene_narration: Scene description string.

        Returns:
            Validated CharacterEngineResponse instance.

        Raises:
            ValueError: If character is missing or LLM returns invalid JSON/AI language.
        """
        character = universe.get_character(character_id)
        if not character:
            raise ValueError(f"Character '{character_id}' not found in Universe.")

        ctx = self.build_context(
            character=character,
            world_state=world_state,
            universe=universe,
            user_action=user_action,
            memories=memories,
            relationships=relationships,
            scene_narration=scene_narration,
        )

        # 1. Format character_response.txt template
        template = self._prompts["character_response.txt"]
        prompt = template
        for k, v in ctx.items():
            prompt = prompt.replace(f"{{{k}}}", v)

        # 2. Call AI Client
        raw_response = self.ai_client.generate(prompt)

        # 3. Parse JSON
        parsed = _parse_json(raw_response)

        dialogue = str(parsed.get("dialogue", "")).strip()
        if not dialogue:
            dialogue = "..."

        # 4. Validate Response (Personality Guard / Meta-Language Check)
        self.validate_response(dialogue)

        return CharacterEngineResponse(
            character_id=character_id,
            dialogue=dialogue,
            emotion=parsed.get("emotion"),
            actions=_as_list(parsed.get("actions")),
            memory_candidates=_as_list(parsed.get("memory_candidates")),
            relationship_changes=_as_list(parsed.get("relationship_changes")),
            world_effects=_as_list(parsed.get("world_effects")),
            follow_up_actions=_as_list(parsed.get("follow_up_actions")),
        )

    def validate_response(self, dialogue: str) -> None:
        """
        Validate character response against meta-language and immersion breaks.

        Raises:
            ValueError: If dialogue contains forbidden AI meta-phrases.
        """
        lower_d = dialogue.lower()
        for phrase in _FORBIDDEN_AI_PHRASES:
            if phrase in lower_d:
                raise ValueError(
                    f"Character response violated immersion by referencing "
                    f"forbidden AI meta-phrase '{phrase}'."
                )


def _parse_json(raw: str) -> dict[str, Any]:
    text = raw.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        text = "\n".join(lines[1:-1]).strip()
    return json.loads(text, strict=False)


def _as_list(val: Any) -> list[Any]:
    if val is None:
        return []
    if isinstance(val, list):
        return val
    return [val]
